image: paritytech/ink-ci-linux

workspaceLocation: "flipper/flipper"

tasks: 
  - init: cd flipper && cargo +nightly contract build

vscode:
  extensions:
    - matklad.rust-analyzer
    - bungcip.better-toml
