image: paritytech/ink-ci-linux

workspaceLocation: "./flipper"

tasks: 
  - command: cargo contract new flipper && cd flipper
  - command: cargo +nightly contract build

vscode:
  extensions:
    - matklad.rust-analyzer
    - bungcip.better-toml
